# Generated by Django 5.1.1 on 2024-09-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name_plural': 'Movies'},
        ),
    ]
