# Generated by Django 5.1.1 on 2024-09-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_system', '0004_director_slug_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.DurationField(),
        ),
    ]
