# Generated by Django 5.1.1 on 2024-09-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_system', '0006_actor_alter_movies_director_review_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='synopsis',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
